apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-app1
  name: nginx-app1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-app1
    spec:
      containers:
      - image: arun6783/app1-nginx
        name: app1-nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-app1
  name: nginx-app1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-app1
status:
  loadBalancer: {}
