apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app1-deployment
  labels:
    app: nginx-app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app1
  template:
    metadata:
      labels:
        app: nginx-app1
    spec:
      containers:
        - name: nginx-app1
          image: aksdevopsacr.azurecr.io/custom2aksnginxapp1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-app1-loadbalancer-service
  labels:
    app: nginx-app1
spec:
  type: LoadBalancer
  selector:
    app: nginx-app1
  ports:
    - port: 80
      targetPort: 80

